import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class PostService {
  lists = [
    {id: 1, title: 'Zoom digital vs. Zoom óptico: descubre las diferencias traen ambas tecnologías en los móviles', description: 'Te explicamos las diferencias que hay en ambos zoom y el provecho que le puedes dar a tu smartphone...', date: '24 MAY 2024 | 18:36 H', image: 'assets/image.png', fullDescription: 'Una de las características más valoradas por los usuarios de dispositivos móviles es, sin duda, el apartado fotográfico que permite capturar imágenes y videos de buena calidad, dependiendo de sus terminaciones técnicas. En este ámbito, el zoom juega un papel fundamental al proporcionar la capacidad de acercar objetos distantes y enfocar detalles que de otro modo podrían escapar a la vista. Dos de las tecnologías más utilizadas en smartphones son el zoom digital y el óptico. El primero aprovecha el poder del software para aumentar el tamaño de la imagen capturada, recortando y ampliando la imagen original. Si bien es versátil, puede perder un poco su calidad, debido a la interpolación de píxeles, especialmente si se realiza un acercamiento significativo. Este tipo de zoom es el más tradicional y lo poseen la mayor parte de móviles de la gama de entrada. Por otro lado, el zoom óptico utiliza lentes físicos para acercar la imagen sin sacrificar la calidad. Este método conserva la nitidez y los detalles, siendo ideal para la fotografía de paisajes o videos de larga distancia. Sin embargo, no tiene la profundidad de acercamiento al nivel del zoom digital. En el mercado, existen dispositivos que pueden incluir ambas tecnologías. Es el caso del Oppo reno 11 5G, uno de los últimos celulares que se han lanzado en el mercado peruano. Este dispositivo posee un zoom óptico de 2X que permite obtener detalles más cercanos sin perder calidad. Para conocer más sobre cada tipo de zoom, los especialistas comparten cuatro diferencias entre ambas tecnologías.'},
  ];
  lists1 = [
    {id: 2, title: 'Combate del 2 de Mayo en el Perú: todo sobre las causas sobre la invación española', description: 'Descubre por qué se originó el Combate del 2 de mayo en el Perú, un evento histórico crucial en la...', date: '02 MAY 2024 | 9:17 H', image: 'assets/image1.png', fullDescription: 'El Combate del 2 de Mayo marca un capítulo fundamental en la historia de la lucha por la independencia en el Perú. En este enfrentamiento, las fuerzas peruanas defendieron el puerto del Callao contra una invasión española, cuyas causas tienen raíces profundas en la historia política y económica tanto de Perú como de España. Además, las disputas financieras entre Perú y España, incluidas las reclamaciones de deudas impagas por parte del gobierno peruano a ciudadanos y empresas españolas, añadieron tensiones adicionales a la relación entre ambos países. En la siguiente nota, te contamos todos los detalles. El Combate del 2 de Mayo, ocurrido el 2 de mayo de 1866 en el Callao, fue un enfrentamiento crucial en la historia del país. En este día, la flota española, comandada por el almirante Casto Méndez Núñez, intentó retomar el control del puerto del Callao, que en ese entonces se encontraba en manos de las fuerzas peruanas. Bajo el liderazgo del Jefe Supremo de la República del Perú, Mariano Ignacio Prado, el escuadrón peruano asumió la responsabilidad de proteger el Callao. Encabezando las operaciones peruanas estaba el coronel José Gálvez, quien ocupaba el cargo de Ministro de Guerra. La confrontación se prolongó durante un período de ocho horas. La armada peruana demostró estar a la altura de las expectativas y logró asegurar la victoria. Este desenlace épico no habría sido posible sin el valor demostrado por José Gálvez, quien, lamentablemente, perdió la vida en combate junto a otros cuarenta compatriotas. Este evento histórico marcó un punto de inflexión en la historia de Perú, fortaleciendo el sentimiento nacionalista y la determinación de defender la soberanía del país contra cualquier amenaza externa.'},
  ];
  lists2 = [
    {id: 3, title: 'Lanzan campaña para promover las carreras de ciencia y tecnología', description: 'Por el "Día de la Mujer" se busca impulsar a las futuras generaciones a reducir la brecha de género en las profesiones...', date: '13 MAR 2024 | 10:41 H', image: 'assets/image2.png', fullDescription: 'En el marco del Día Internacional de la Mujer, el centro comercial Open Plaza anunció la campaña “Mujeres a la Cima”, una novedosa iniciativa destinada a promover y apoyar la participación de las mujeres peruanas en carreras de Ciencia, Tecnología, Ingeniería y Matemáticas (STEM).Para demostrarlo, el centro comercial utilizó la famosa plataforma de videojuego Fortnite, la creación del mapa estuvo a cargo de la gamer peruana @Tepharc en colaboración con Diego Leguía, quienes diseñaron un centro comercial inspirado en los centros Open Angamos en Lima y Open Kennedy en Santiago. Cabe destacar que esta experiencia de Fortnite ha sido creada de forma independiente y no está patrocinada, promocionada o gestionada por Epic Games, Inc. Para Erika Wicht gerente de Marketing regional, esta iniciativa busca que desde el público más joven hasta adultos logren destacar la importancia de las oportunidades que tienen las mujeres en diversas carreras profesionales. “Sabemos que de acuerdo a SUNEDU, las mujeres representan solo 29.2% del total de estudiantes matriculados en carreras de Ciencia, Tecnología e Innovación en Perú. Existe el mito que los hombres tienen mayor afinidad con estas carreras profesionales y debemos revertir esa concepción, abriendo paso a las nuevas generaciones”, indicó.'},
  ];
  lists3 = [
    {id: 4, title: 'Soñar con tu padre fallecido: Qué significa y cómo interpretar el mensaje oculto', description: 'Descubre el verdadero significado emocional de soñar con tu padre fallecido y cómo...', date: '30 MAY 2024 | 10:56 H', image: 'assets/image3.png', fullDescription: 'Este sueño, sin duda, debe ser uno de los más trágicos y angustiosos para las personas que lo ha soñado, ya que normalmente el fallecimiento suele estar relacionado con la señal de un mal presagio o algo negativo. Sin embargo, es muy importante saber el contexto específico del sueño para determinar una interpretación correcta del momento onírico. Cabe mencionar que soñar con papá fallecido también está relacionado con la inseguridad ante una determinada situación. Es por ello que en la siguiente nota te damos a conocer las diferentes interpretaciones que tiene este sueño. Los sueños con un padre fallecido pueden desempeñar un papel importante en el proceso de duelo. Para muchas personas, estos sueños brindan una sensación de conexión y consuelo que puede ser profundamente sanadora. En estos sueños, es posible experimentar una sensación de cercanía con el ser querido fallecido, como si estuvieran realmente presentes. Esto puede proporcionar un espacio para expresar emociones no resueltas, decir adiós o incluso recibir orientación y apoyo espiritual. Además, los sueños con un padre fallecido pueden ayudar a las personas a procesar su pena y aceptar la realidad de la pérdida. Pueden brindar una sensación de cierre emocional o confirmar que el ser querido está en paz.'},
  ];

  getAllPosts(): any[] {
    return [
      ...this.lists,
      ...this.lists1,
      ...this.lists2,
      ...this.lists3
    ];
  }

  getPostById(id: number): any {
    const allPosts = this.getAllPosts();
    return allPosts.find(post => post.id === id);
  }
}